import React, { useState, useEffect } from 'react';
import { X, ExternalLink, Save, Plus, BarChart3, Table2, Loader } from 'lucide-react';

const API_BASE = process.env.REACT_APP_API_URL || '';

/**
 * MetabasePushModal — Push RAVEN SQL results to Metabase.
 * Three actions: Save as question, Add to dashboard, Save to collection.
 */
export default function MetabasePushModal({ visible, sql, question, chartType, onClose }) {
  const [mode, setMode] = useState('question'); // 'question' | 'dashboard' | 'collection'
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [display, setDisplay] = useState('table');
  const [dashboards, setDashboards] = useState([]);
  const [collections, setCollections] = useState([]);
  const [selectedDashboard, setSelectedDashboard] = useState(null);
  const [selectedCollection, setSelectedCollection] = useState(null);
  const [pushing, setPushing] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState('');

  useEffect(() => {
    if (visible) {
      setName(question ? question.slice(0, 100) : 'RAVEN Query');
      setDescription(`Generated by RAVEN`);
      setDisplay(chartType === 'LINE' ? 'line' : chartType === 'BAR' ? 'bar' : chartType === 'PIE' ? 'pie' : 'table');
      setResult(null);
      setError('');
      // Load dashboards and collections
      Promise.all([
        fetch(`${API_BASE}/api/metabase/dashboards`).then(r => r.json()).catch(() => ({ dashboards: [] })),
        fetch(`${API_BASE}/api/metabase/collections`).then(r => r.json()).catch(() => ({ collections: [] })),
      ]).then(([d, c]) => {
        setDashboards(d.dashboards || []);
        setCollections(c.collections || []);
      });
    }
  }, [visible, question, chartType]);

  const handlePush = async () => {
    setPushing(true);
    setError('');
    try {
      let endpoint, body;
      if (mode === 'question') {
        endpoint = '/api/metabase/push-question';
        body = { name, sql, display, description, collection_id: selectedCollection };
      } else if (mode === 'dashboard') {
        endpoint = '/api/metabase/add-to-dashboard';
        body = { name, sql, display, dashboard_id: selectedDashboard };
      }
      const resp = await fetch(`${API_BASE}${endpoint}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });
      if (!resp.ok) throw new Error((await resp.json()).detail || `HTTP ${resp.status}`);
      setResult(await resp.json());
    } catch (e) {
      setError(e.message);
    } finally {
      setPushing(false);
    }
  };

  if (!visible) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content metabase-push-modal" onClick={e => e.stopPropagation()}>
        <div className="modal-header">
          <h3><BarChart3 size={16} /> Push to Metabase</h3>
          <button className="btn-icon" onClick={onClose}><X size={16} /></button>
        </div>

        {result ? (
          <div className="metabase-push-result">
            <div className="metabase-push-success">
              <Save size={20} />
              <span>Saved to Metabase!</span>
            </div>
            {result.url && (
              <a href={result.url} target="_blank" rel="noopener noreferrer" className="metabase-push-link">
                <ExternalLink size={14} /> Open in Metabase
              </a>
            )}
            <button className="btn-secondary" onClick={onClose} style={{ marginTop: 12 }}>Close</button>
          </div>
        ) : (
          <>
            <div className="metabase-push-tabs">
              <button
                className={`metabase-push-tab ${mode === 'question' ? 'active' : ''}`}
                onClick={() => setMode('question')}
              >
                <Save size={13} /> Save as Question
              </button>
              <button
                className={`metabase-push-tab ${mode === 'dashboard' ? 'active' : ''}`}
                onClick={() => setMode('dashboard')}
              >
                <Plus size={13} /> Add to Dashboard
              </button>
            </div>

            <div className="metabase-push-form">
              <label>
                Name
                <input
                  type="text"
                  value={name}
                  onChange={e => setName(e.target.value)}
                  placeholder="Question name"
                />
              </label>

              <label>
                Description
                <input
                  type="text"
                  value={description}
                  onChange={e => setDescription(e.target.value)}
                  placeholder="Description"
                />
              </label>

              <label>
                Visualization
                <select value={display} onChange={e => setDisplay(e.target.value)}>
                  <option value="table">Table</option>
                  <option value="bar">Bar Chart</option>
                  <option value="line">Line Chart</option>
                  <option value="pie">Pie Chart</option>
                  <option value="scalar">Number Card</option>
                  <option value="row">Horizontal Bar</option>
                  <option value="area">Area Chart</option>
                  <option value="scatter">Scatter</option>
                </select>
              </label>

              {mode === 'question' && collections.length > 0 && (
                <label>
                  Collection
                  <select
                    value={selectedCollection || ''}
                    onChange={e => setSelectedCollection(e.target.value ? Number(e.target.value) : null)}
                  >
                    <option value="">Default (RAVEN Generated)</option>
                    {collections.map(c => (
                      <option key={c.id} value={c.id}>{c.name}</option>
                    ))}
                  </select>
                </label>
              )}

              {mode === 'dashboard' && (
                <label>
                  Dashboard
                  <select
                    value={selectedDashboard || ''}
                    onChange={e => setSelectedDashboard(e.target.value ? Number(e.target.value) : null)}
                  >
                    <option value="">Select a dashboard...</option>
                    {dashboards.map(d => (
                      <option key={d.id} value={d.id}>{d.name}</option>
                    ))}
                  </select>
                </label>
              )}

              <div className="metabase-push-sql-preview">
                <strong>SQL Preview:</strong>
                <pre>{sql?.slice(0, 300)}{sql?.length > 300 ? '...' : ''}</pre>
              </div>

              {error && <div className="metabase-push-error">{error}</div>}

              <div className="metabase-push-actions">
                <button className="btn-secondary" onClick={onClose}>Cancel</button>
                <button
                  className="metabase-push-submit"
                  onClick={handlePush}
                  disabled={pushing || !name.trim() || (mode === 'dashboard' && !selectedDashboard)}
                >
                  {pushing ? <><Loader size={14} className="spin" /> Saving...</> : <><Save size={14} /> Save to Metabase</>}
                </button>
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
