"""
RAVEN Metabase Client — API integration with Metabase BI.
==========================================================
Supports: test connection, create/list questions & dashboards,
          fetch dashboard cards for Focus Mode context.
"""

from __future__ import annotations

import logging
import re
from typing import Any

logger = logging.getLogger(__name__)

# Visualization mapping: RAVEN chart type → Metabase display type
VIZ_MAPPING = {
    "number_card": "scalar",
    "line_chart": "line",
    "bar_chart": "bar",
    "horizontal_bar": "row",
    "pie_chart": "pie",
    "scatter": "scatter",
    "table": "table",
    "TABLE": "table",
    "LINE": "line",
    "BAR": "bar",
    "PIE": "pie",
    "SCATTER": "scatter",
    "AREA": "area",
}


def _parse_tables_from_sql(sql: str) -> list[str]:
    """Best-effort extraction of table names from SQL."""
    pattern = r'(?:FROM|JOIN)\s+([a-zA-Z_][a-zA-Z0-9_.]*)'
    matches = re.findall(pattern, sql, re.IGNORECASE)
    return list(dict.fromkeys(matches))  # dedupe, preserve order


class MetabaseClient:
    """Async HTTP client for the Metabase REST API."""

    def __init__(self, url: str, session_id: str | None = None,
                 api_key: str | None = None):
        self.url = url.rstrip("/")
        self.headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self.headers["X-Api-Key"] = api_key
        elif session_id:
            self.headers["X-Metabase-Session"] = session_id

    # ── HTTP helpers ───────────────────────────────────────────

    async def _get(self, path: str) -> Any:
        import aiohttp
        async with aiohttp.ClientSession(headers=self.headers) as session:
            async with session.get(f"{self.url}{path}") as resp:
                resp.raise_for_status()
                return await resp.json()

    async def _post(self, path: str, data: dict) -> Any:
        import aiohttp
        async with aiohttp.ClientSession(headers=self.headers) as session:
            async with session.post(f"{self.url}{path}", json=data) as resp:
                resp.raise_for_status()
                return await resp.json()

    async def _put(self, path: str, data: dict) -> Any:
        import aiohttp
        async with aiohttp.ClientSession(headers=self.headers) as session:
            async with session.put(f"{self.url}{path}", json=data) as resp:
                resp.raise_for_status()
                return await resp.json()

    # ── Connection ─────────────────────────────────────────────

    async def test_connection(self) -> dict:
        """Test connection; return user name, dashboard/question counts."""
        try:
            user = await self._get("/api/user/current")
            dashboards = await self._get("/api/dashboard")
            collections = await self._get("/api/collection")
            return {
                "connected": True,
                "user": user.get("common_name", "Unknown"),
                "dashboards": len(dashboards) if isinstance(dashboards, list) else 0,
                "collections": len(collections) if isinstance(collections, list) else 0,
            }
        except Exception as e:
            logger.warning("Metabase connection test failed: %s", e)
            return {"connected": False, "error": str(e)}

    # ── Questions (saved cards) ────────────────────────────────

    async def create_question(self, name: str, sql: str, display: str,
                               database_id: int, collection_id: int | None = None,
                               description: str | None = None) -> dict:
        """Create a saved question (native query)."""
        display = VIZ_MAPPING.get(display, display)
        payload: dict[str, Any] = {
            "name": name,
            "description": description or "Generated by RAVEN",
            "dataset_query": {
                "type": "native",
                "native": {"query": sql, "template-tags": {}},
                "database": database_id,
            },
            "display": display,
            "visualization_settings": self._default_viz_settings(display),
        }
        if collection_id:
            payload["collection_id"] = collection_id
        resp = await self._post("/api/card", payload)
        return {
            "id": resp["id"],
            "url": f"{self.url}/question/{resp['id']}",
            "name": name,
        }

    async def get_question(self, question_id: int) -> dict:
        """Fetch a single Metabase question/card."""
        card = await self._get(f"/api/card/{question_id}")
        sql = ""
        if card.get("dataset_query", {}).get("type") == "native":
            sql = card["dataset_query"]["native"].get("query", "")
        return {
            "card_id": card["id"],
            "name": card.get("name", ""),
            "sql": sql,
            "display": card.get("display", "table"),
            "tables": _parse_tables_from_sql(sql) if sql else [],
            "description": card.get("description", ""),
        }

    # ── Dashboards ─────────────────────────────────────────────

    async def list_dashboards(self) -> list[dict]:
        dashboards = await self._get("/api/dashboard")
        return [
            {
                "id": d["id"],
                "name": d.get("name", ""),
                "description": d.get("description", ""),
            }
            for d in dashboards
            if not d.get("archived")
        ]

    async def get_dashboard_meta(self, dashboard_id: int) -> dict:
        """Fetch dashboard metadata (name, filters, owner, database_id)."""
        d = await self._get(f"/api/dashboard/{dashboard_id}")
        # Auto-detect database_id from the first native card
        db_id = None
        for dc in d.get("dashcards", []):
            card = dc.get("card", {})
            dq = card.get("dataset_query", {})
            if dq.get("database"):
                db_id = dq["database"]
                break
        return {
            "id": d["id"],
            "name": d.get("name", ""),
            "description": d.get("description", ""),
            "filters": d.get("parameters", []),
            "owner": d.get("creator", {}).get("common_name", ""),
            "card_count": len(d.get("dashcards", [])),
            "database_id": db_id,
        }

    async def get_dashboard_cards(self, dashboard_id: int) -> list[dict]:
        """Get all native-query cards from a dashboard (for Focus Mode)."""
        dashboard = await self._get(f"/api/dashboard/{dashboard_id}")
        cards = []
        for dc in dashboard.get("dashcards", []):
            card = dc.get("card", {})
            if card.get("dataset_query", {}).get("type") == "native":
                sql = card["dataset_query"]["native"].get("query", "")
                cards.append({
                    "card_id": card["id"],
                    "name": card.get("name", ""),
                    "sql": sql,
                    "display": card.get("display", "table"),
                    "tables": _parse_tables_from_sql(sql),
                })
        return cards

    async def create_dashboard(self, name: str, card_ids: list[int],
                                collection_id: int | None = None,
                                description: str | None = None) -> dict:
        """Create a dashboard and lay out cards in a 2-column grid."""
        payload: dict[str, Any] = {
            "name": name,
            "description": description or "Generated by RAVEN",
        }
        if collection_id:
            payload["collection_id"] = collection_id
        dashboard = await self._post("/api/dashboard", payload)
        dashboard_id = dashboard["id"]

        # Lay out cards — 2 per row, each 9 wide × 4 tall (out of 18 grid units)
        dashcards = []
        for i, card_id in enumerate(card_ids):
            row = (i // 2) * 4
            col = (i % 2) * 9
            dashcards.append({
                "id": -1,
                "card_id": card_id,
                "row": row,
                "col": col,
                "size_x": 9,
                "size_y": 4,
            })
        await self._put(f"/api/dashboard/{dashboard_id}", {
            "dashcards": dashcards,
        })
        return {
            "id": dashboard_id,
            "url": f"{self.url}/dashboard/{dashboard_id}",
            "name": name,
            "card_count": len(card_ids),
        }

    async def add_card_to_dashboard(self, dashboard_id: int, card_id: int) -> dict:
        """Add an existing question to a dashboard at the bottom."""
        dashboard = await self._get(f"/api/dashboard/{dashboard_id}")
        existing = dashboard.get("dashcards", [])
        max_row = max(
            [dc.get("row", 0) + dc.get("size_y", 4) for dc in existing],
            default=0,
        )
        new_card = {
            "id": -1,
            "card_id": card_id,
            "row": max_row,
            "col": 0,
            "size_x": 18,
            "size_y": 4,
        }
        await self._put(f"/api/dashboard/{dashboard_id}", {
            "dashcards": existing + [new_card],
        })
        return {"dashboard_url": f"{self.url}/dashboard/{dashboard_id}"}

    # ── Collections ────────────────────────────────────────────

    async def list_collections(self) -> list[dict]:
        collections = await self._get("/api/collection")
        return [
            {"id": c["id"], "name": c.get("name", "")}
            for c in collections
            if not c.get("archived")
        ]

    async def get_collection_meta(self, collection_id: int) -> dict:
        """Fetch a single collection for sync/preview naming."""
        collection = await self._get(f"/api/collection/{collection_id}")
        return {
            "id": collection.get("id", collection_id),
            "name": collection.get("name", f"Collection #{collection_id}"),
            "description": collection.get("description", ""),
        }

    async def get_collection_items(self, collection_id: int) -> list[dict]:
        """Fetch all native-query cards in a collection."""
        items = await self._get(f"/api/collection/{collection_id}/items?models=card")
        result = []
        for item in items.get("data", items if isinstance(items, list) else []):
            if item.get("model") == "card" or item.get("id"):
                try:
                    card = await self.get_question(item["id"])
                    if card.get("sql"):
                        result.append(card)
                except Exception:
                    continue
        return result

    # ── Helpers ────────────────────────────────────────────────

    def _default_viz_settings(self, display: str) -> dict:
        if display in ("line", "bar", "area"):
            return {"graph.dimensions": ["x"], "graph.metrics": ["y"]}
        elif display == "pie":
            return {"pie.dimension": "x", "pie.metric": "y"}
        return {}
