apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgvector-pvc
  namespace: raven
  labels:
    app: raven
    component: pgvector
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
